Auto indent
justy989/ce_old pull request #28
Opened 2016-10-02 01:52 UTC by ryabouza

Enter, O, and o now auto indent.

I'm sure there's some crazy edge cases, but we can address them as they pop up.

2016-10-03 15:46 UTC, robber-m commented on ce.c
> +bool ce_move_cursor_to_soft_end_of_line(Buffer* buffer, Point* cursor)
What is the soft end of line?

2016-10-03 15:46 UTC, robber-m commented on ce.c
> +// if there is not a sbol, returns eol
Does this mean if a line is all blanks?

2016-10-03 15:46 UTC, robber-m commented on ce.h
> +     ({ __typeof__ (a) _a = (a); \
Great job with macro safety. One suggestion I have is to change these to be `CE_MAX` and `CE_MIN` to avoid name conflicts with other headers

2016-10-03 15:46 UTC, robber-m commented on ce_config.c
> +                                   ce_remove_string(buffer, cursor, n_deletes);
This won't be undoable if you don't `ce_commit_remove_string`

2016-10-03 15:46 UTC, robber-m commented on ce_config.c
> +                         if(ce_insert_string(buffer, cursor, indent))
will need to `ce_commit_insert_string`

2016-10-03 15:46 UTC, robber-m commented on ce_config.c
> +                                   ce_remove_string(buffer, cursor, n_deletes);
Nvm. I'm wrong. This is for insert mode. ignore me

2016-10-03 15:46 UTC, robber-m commented on ce_config.c
> +                         if(ce_insert_string(buffer, cursor, indent))
nvm. I'm wrong.

2016-10-03 15:46 UTC, robber-m commented on ce_config.c
> +                    cursor->x = indent_len;
Do you need to do this before you call `ce_commit_insert_string`? It feels to me like the redo cursor will be in the wrong spot

2016-10-03 15:46 UTC, robber-m commented on ce_config.c
> +                    cursor->x = indent_len;
I think you need start to be `&begin_line`, `undo_cursor` to be `cursor`, and redo cursor to be `{indent_len, cursor->y}`

2016-10-03 16:25 UTC, ryabouza commented on ce.c
> +bool ce_move_cursor_to_soft_end_of_line(Buffer* buffer, Point* cursor)
"    meow    "
'w' is

2016-10-03 16:25 UTC, ryabouza commented on ce.c
> +// if there is not a sbol, returns eol
Yes.

2016-10-03 16:33 UTC, ryabouza commented on ce_config.c
> +                    cursor->x = indent_len;
Good catch!

2016-10-03 17:52 UTC, bobbymcshane commented
Just waiting on the `MAX` name change to `CE_MAX`

2016-10-03 17:56 UTC, robber-m requested changes
`MAX` => `CE_MAX`, `MIN` => `CE_MIN`

2016-10-03 17:56 UTC, robber-m approved these changes

2016-10-03 17:58 UTC, robber-m requested changes
`MAX` => `CE_MAX`, `MIN` => `CE_MIN`

2016-10-04 14:33 UTC, robber-m approved these changes

2016-10-04 17:36 UTC, merged