Keypad + backspace
justy989/ce_old pull request #49
Opened 2016-10-05 18:30 UTC by ryabouza

KEY_* enumerations in the curses headers seem to be generated from an OS specific file.  On OSX, ^H seems to be the
typical backspace character, however nowadays terminals send the Linux ^? in order to be compatible with other machines
when SSHing. With keypad off, curses interpets both ^H and ^? as key code 127. With keypad on, the interpretted code
depends on the system specific header. For Justin, backspace (^? on Linux) was being correctly converted to
KEY_BACKSPACE (value 263) by curses, but we we're handling that value in ce_config. For me, backspace (normally ^H on
Mac, but ^? in my case) was unabled to be mapped, and defaulted to value 127 which we were handling in the ce_config as
the backspace operation.

We now look for the KEY_BACKSPACE value when interpreting keys, and I've changed the settings in my terminal to send
^H as backspace. Maybe we should also support the raw 127 value?

2016-10-05 23:29 UTC, justy989 commented
"scroll up" support coming in the next ncurses release in 2018

2016-10-06 01:04 UTC, ryabouza commented
SCROLL'N ALL OVAH DAH PLACE

Can someone test this on Linux please?

2016-10-06 03:12 UTC, justy989 commented
scroll up words for me, but not scroll down :crying_cat_face:

2016-10-06 03:26 UTC, ryabouza commented
I have some ideas for how to fix. I'll need your assistance tomorrow!

On Wed, Oct 5, 2016, 11:12 PM Justin Tardiff <notifications@github.com>
wrote:

> scroll up words for me, but not scroll down 😿
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/justy989/ce/pull/49#issuecomment-251857075>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHtxgaEaRrRxcegEqlV4g7q8OJ3LJcssks5qxGcigaJpZM4KPIxN>
> .
>

2016-10-06 11:04 UTC, robber-m requested changes

2016-10-06 11:04 UTC, bobbymcshane commented on ce_config.c
> +               ce_remove_char(buffer, cursor);
@justy989 does this screw up undo?

2016-10-06 11:04 UTC, bobbymcshane commented on ce_config.c
> +                              if(buffer_view->cursor.y > buffer_view->top_row + (buffer_view->bottom_right.y - buffer_view->top_left.y))
Doesn't `ce_move_cursor` take care of this bounds checking for you? not a big deal, but it would simplify the config logic a bit if we could get rid of that `if`

2016-10-06 11:04 UTC, bobbymcshane commented on ce_config.c
> +                              if(buffer_view->cursor.y < buffer_view->top_row)
I think we can delete this if. `ce_move_cursor` should be able to handle the bounds checking

2016-10-06 11:04 UTC, bobbymcshane commented on ce_config.c
> +          case KEY_MOUSE:
I don't think our undo logic is able to support this kind of movement in insert mode at the moment. I think you could support it, however, if you made a mouse movement in insert mode leave insert mode (via `esc` key logic) and re-enter insert mode after the mouse movement.

```
leave_insert_mode(); // this will correctly save the undo state
BufferView* prev_view = config_state->view_current;
do_mouse_movement();
if(config_state->view_current == prev_view){
     enter_insert_mode();
}

2016-10-06 11:04 UTC, bobbymcshane commented on ce_config.c
> +               MEVENT event;
This code should probably be unified with the insert mode mouse handling code

2016-10-06 11:22 UTC, ryabouza commented on ce_config.c
> +          case KEY_MOUSE:
Yeah, Justin mentioned that would be a problem yesterday. That's an interesting  solution!

2016-10-06 11:23 UTC, ryabouza commented on ce_config.c
> +               ce_remove_char(buffer, cursor);
I thought I tested it, but I don't remember. I'll check again.

2016-10-06 11:23 UTC, ryabouza commented on ce_config.c
> +               MEVENT event;
Agreed.

2016-10-06 11:31 UTC, ryabouza commented on ce_config.c
> +                              if(buffer_view->cursor.y > buffer_view->top_row + (buffer_view->bottom_right.y - buffer_view->top_left.y))
The ce_point_on_buffer check lets us know whether we can even scroll at all, or if we're at the first or last line in the buffer (in which case scrolling is not an option). If we scroll down successfully, we check if the cursor fell off the view after scrolling, and move the cursor to keep it in the view.

This logic looks a little funny to me this morning. I'll review it in a bit.

2016-10-06 11:32 UTC, ryabouza commented on ce_config.c
> +                              if(buffer_view->cursor.y < buffer_view->top_row)
I thought it only handled buffer checking, and not view checking? Will review.

2016-10-06 11:46 UTC, bobbymcshane commented on ce_config.c
> +                              if(buffer_view->cursor.y > buffer_view->top_row + (buffer_view->bottom_right.y - buffer_view->top_left.y))
Makes sense. I was missing the intent of your `if`. I needed to read more carefully

2016-10-06 11:46 UTC, robber-m commented on ce_config.c
> +                              if(buffer_view->cursor.y < buffer_view->top_row)
You're correct. My bad

2016-10-06 11:50 UTC, ryabouza commented on ce_config.c
> +                              if(buffer_view->cursor.y > buffer_view->top_row + (buffer_view->bottom_right.y - buffer_view->top_left.y))
Or, you know, I could comment :P

2016-10-06 21:02 UTC, ryabouza commented
@justy989 I think this is ready to go.

2016-10-06 22:46 UTC, justy989 approved these changes

2016-10-06 23:04 UTC, robber-m approved these changes

2016-10-06 23:05 UTC, merged