Feature/replace
justy989/ce_old pull request #70
Opened 2016-10-08 04:04 UTC by justy989

2016-10-08 12:21 UTC, robber-m requested changes

2016-10-08 12:21 UTC, bobbymcshane commented on ce_config.c
> +                         center_view(config_state->tab_current->view_input_save);
Awesome!

2016-10-08 12:21 UTC, bobbymcshane commented on ce_config.c
> +                         char* replace_str = ce_dupe_buffer(config_state->view_input->buffer);
I'm missing something. Where did the input buffer get opened and populated?

2016-10-08 12:21 UTC, bobbymcshane commented on ce_config.c
> +                    case 1: // Ctrl + a
This is great too!

2016-10-08 12:21 UTC, bobbymcshane commented on ce_config.c
> +               input_start(config_state, "Replace", key);
Disregard my previous question

2016-10-08 12:21 UTC, bobbymcshane commented on ce_config.c
> +               input_start(config_state, "Replace", key);
I'm looking on my phone so it was hard to see that we were in the end input mode case above

2016-10-08 12:21 UTC, bobbymcshane commented on ce_config.c
> +               }
I'm excited for this. I love incsearch

2016-10-08 12:21 UTC, bobbymcshane commented on ce_config.c
> +     if(view == current_view) printw("%s %d ", keyname(last_key), last_key);
`#ifndef NDEBUG`

2016-10-09 14:38 UTC, justy989 commented on ce_config.c
> +     if(view == current_view) printw("%s %d ", keyname(last_key), last_key);
done !

2016-10-11 14:54 UTC, robber-m approved these changes

2016-10-11 14:54 UTC, merged